/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package prySinglenton;

public class App {
    /*public String getGreeting() {
        return "Hello World!";
    }*/

    public static void main(String[] args) {
        Inventario i=Inventario.getInstance();
        
        i.agregarProducto(new Producto("2101","sopa","pasta",20,2));
        //i.eliminarPrducto(i);
        //i.editarProducto(p, 0);
        //i.buscarProductoPorIndice(i);
        
        /*
        eliminar producto,editar producto y buscarlo pueden
        activarse cuando tengamos un lista con mas productos
        o para realizarse una prueba.
        Eliminar
        */
    }
}
